import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const docLinks = [
  {
    text: "Server Side Rendered Page",
    url: "/ssr",
  },
  {
    text: "Statically Generated Page",
    url: "/ssg",
  },
  {
    text: "Incremental Static Regeneration Page",
    url: "/isr",
  },
  {
    text: "Rick and morty (Statically generated using graphql) Page",
    url: "/rickandmorty",
  },
  {
    text: "Image Optimization",
    url: "/img-opt",
  }
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.grid}>
          {docLinks.map((doc) => (
            <li key={doc.url} className={styles.docLinkStyle}>
              <a className={styles.linkStyle} href={`${doc.url}`}>
                {doc.text}
              </a>
            </li>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
