import * as React from "react";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const IncrementalStaticPage: NextPage<any> = ({ data }) => {
  const date = new Date();
  console.log("generated: " + date.getHours(),date.getMinutes(),date.getSeconds());
  return (
    <div className={styles.container}>
      <Head>
        <title>Incremental Statically Generated Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Incremental Statically Generated Page</h1>
        <div className={styles.grid}>
          {data.status === "success" &&
            data.message.map((img_url: string, ind: number) => {
              return (
                <Image
                  key={ind}
                  src={img_url}
                  alt={`Image URL`}
                  height={200}
                  width={200}
                />
              );
            })}
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (): Promise<any> => {
  const res = await fetch("https://dog.ceo/api/breeds/image/random/5");
  const data = await res.json();

  return {
    props: {
      data,
    },
    revalidate: 60,
  };
};

export default IncrementalStaticPage;
