import * as React from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const ServerSidePage: NextPage<any> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Server Side Rendered Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Server Side Rendered Page</h1>
        <div className={styles.grid}>
          {data.status === "success" &&
            data.message.map((img_url: string, ind: number) => {
              return (
                <Image
                  key={ind}
                  src={img_url}
                  alt={`Image URL`}
                  height={200}
                  width={200}
                />
              );
            })}
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps =
  async (): Promise<any> => {
    const res = await fetch("https://dog.ceo/api/breeds/image/random/5");
    const data = await res.json();

    return {
      props: {
        data,
      },
    };
  };

export default ServerSidePage;
